export default {
  H: 'RESIDENTAL',
  X: 'RESIDENTAL',
  C: 'CORPORATE',
  D: 'DEPOT',
  P: 'PICKUP',
  GP: 'PERSONAL DELIVERY',
  DI: 'PERSONAL DELIVERY',
  GC: 'PROFESSIONAL DELIVERY',
  DB: 'PROFESSIONAL DELIVERY'
};
